apiVersion: v1
kind: PersistentVolume
metadata:
  name: x11
spec:
  storageClassName: local-storage
  local:
    path: /tmp/.X11-unix
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: agent
          operator: In
          values: [env]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: env
spec:
  storageClassName: local-storage
  local:
    path: /home/airobots/aiRobots/pytorch/MARL
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: agent
          operator: In
          values: [env]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model
spec:
  storageClassName: local-storage
  local:
    path: /home/airobots/aiRobots/pytorch/MARL
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: agent
          operator: In
          values: [model]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: x11
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: env
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Mi

  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi