apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agv
  labels:
    app: agv
spec:
  selector:
    matchLabels:
      app: agv
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: agv
    spec:
      nodeSelector:
        agent: agv
      hostNetwork: true
      containers:
      - name: agv
        image: axyz1288/agv
        securityContext:
          runAsUser: 1000
          privileged: true
        ports:
        - containerPort: 11311
        # hostport is useless, because l4t kernel didn't support iptable.
        resources:
          requests:
            memory: "100Mi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "4"
        volumeMounts:
        - name: dev
          mountPath: /dev
        env:
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ROS_IP
          value: $(MY_NODE_IP)
        - name: ROS_MASTER_URI
          value: http://192.168.50.193:11311
        args: ["~/mini_agv/build/agv", "$(MY_NODE_IP)", "gacomm"]
      volumes:
      - name: dev
        persistentVolumeClaim:
          claimName: dev