apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: car
  labels:
    app: car
spec:
  selector:
    matchLabels:
      app: car
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: car
    spec:
      nodeSelector:
        agent: car
      hostNetwork: true
      containers:
      - name: car
        image: axyz1288/car
        securityContext:
          runAsUser: 1000
          privileged: true
        ports:
        - containerPort: 11311
        resources:
          requests:
            memory: "100Mi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "4"
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: car
          mountPath: /home/aiRobots
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ROS_IP
          value: $(MY_NODE_IP)
        - name: ROS_MASTER_URI
          value: http://192.168.50.193:11311
        args: ["~/car/build/car", "$(MY_NODE_NAME)", "gacomm"]
      volumes:
      - name: dev
        persistentVolumeClaim:
          claimName: dev
      - name: car
        persistentVolumeClaim:
          claimName: car